// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// multiply_binomial_coefficient
double multiply_binomial_coefficient(const double x, const std::size_t n, const std::size_t k);
RcppExport SEXP _cvalr_multiply_binomial_coefficient(SEXP xSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::size_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::size_t >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_binomial_coefficient(x, n, k));
    return rcpp_result_gen;
END_RCPP
}
// is_qmatrix
bool is_qmatrix(const NumericMatrix& x, const double tol);
RcppExport SEXP _cvalr_is_qmatrix(SEXP xSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(is_qmatrix(x, tol));
    return rcpp_result_gen;
END_RCPP
}
// portfolio_cds_coupon
double portfolio_cds_coupon(const NumericVector& expected_losses, const NumericVector& times, const NumericVector& discount_factors, const double recovery_rate);
RcppExport SEXP _cvalr_portfolio_cds_coupon(SEXP expected_lossesSEXP, SEXP timesSEXP, SEXP discount_factorsSEXP, SEXP recovery_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type expected_losses(expected_lossesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type discount_factors(discount_factorsSEXP);
    Rcpp::traits::input_parameter< const double >::type recovery_rate(recovery_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(portfolio_cds_coupon(expected_losses, times, discount_factors, recovery_rate));
    return rcpp_result_gen;
END_RCPP
}
// portfolio_cds_upfront
double portfolio_cds_upfront(const NumericVector& expected_losses, const NumericVector& times, const NumericVector& discount_factors, const double recovery_rate, const double coupon);
RcppExport SEXP _cvalr_portfolio_cds_upfront(SEXP expected_lossesSEXP, SEXP timesSEXP, SEXP discount_factorsSEXP, SEXP recovery_rateSEXP, SEXP couponSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type expected_losses(expected_lossesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type discount_factors(discount_factorsSEXP);
    Rcpp::traits::input_parameter< const double >::type recovery_rate(recovery_rateSEXP);
    Rcpp::traits::input_parameter< const double >::type coupon(couponSEXP);
    rcpp_result_gen = Rcpp::wrap(portfolio_cds_upfront(expected_losses, times, discount_factors, recovery_rate, coupon));
    return rcpp_result_gen;
END_RCPP
}
// portfolio_cds_equation
double portfolio_cds_equation(const NumericVector& expected_losses, const NumericVector& times, const NumericVector& discount_factors, const double recovery_rate, const double coupon, const double upfront);
RcppExport SEXP _cvalr_portfolio_cds_equation(SEXP expected_lossesSEXP, SEXP timesSEXP, SEXP discount_factorsSEXP, SEXP recovery_rateSEXP, SEXP couponSEXP, SEXP upfrontSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type expected_losses(expected_lossesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type discount_factors(discount_factorsSEXP);
    Rcpp::traits::input_parameter< const double >::type recovery_rate(recovery_rateSEXP);
    Rcpp::traits::input_parameter< const double >::type coupon(couponSEXP);
    Rcpp::traits::input_parameter< const double >::type upfront(upfrontSEXP);
    rcpp_result_gen = Rcpp::wrap(portfolio_cds_equation(expected_losses, times, discount_factors, recovery_rate, coupon, upfront));
    return rcpp_result_gen;
END_RCPP
}
// cdo_upfront
double cdo_upfront(const NumericVector& expected_losses, const NumericVector& times, const NumericVector& discount_factors, const double lower, const double upper, const double coupon);
RcppExport SEXP _cvalr_cdo_upfront(SEXP expected_lossesSEXP, SEXP timesSEXP, SEXP discount_factorsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP couponSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type expected_losses(expected_lossesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type discount_factors(discount_factorsSEXP);
    Rcpp::traits::input_parameter< const double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const double >::type coupon(couponSEXP);
    rcpp_result_gen = Rcpp::wrap(cdo_upfront(expected_losses, times, discount_factors, lower, upper, coupon));
    return rcpp_result_gen;
END_RCPP
}
// cdo_coupon
double cdo_coupon(const NumericVector& expected_losses, const NumericVector& times, const NumericVector& discount_factors, const double lower, const double upper);
RcppExport SEXP _cvalr_cdo_coupon(SEXP expected_lossesSEXP, SEXP timesSEXP, SEXP discount_factorsSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type expected_losses(expected_lossesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type discount_factors(discount_factorsSEXP);
    Rcpp::traits::input_parameter< const double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(cdo_coupon(expected_losses, times, discount_factors, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// cdo_equation
double cdo_equation(const NumericVector& expected_losses, const NumericVector& times, const NumericVector& discount_factors, const double lower, const double upper, const double coupon, const double upfront);
RcppExport SEXP _cvalr_cdo_equation(SEXP expected_lossesSEXP, SEXP timesSEXP, SEXP discount_factorsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP couponSEXP, SEXP upfrontSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type expected_losses(expected_lossesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type times(timesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type discount_factors(discount_factorsSEXP);
    Rcpp::traits::input_parameter< const double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const double >::type coupon(couponSEXP);
    Rcpp::traits::input_parameter< const double >::type upfront(upfrontSEXP);
    rcpp_result_gen = Rcpp::wrap(cdo_equation(expected_losses, times, discount_factors, lower, upper, coupon, upfront));
    return rcpp_result_gen;
END_RCPP
}
// ex_intensities2qmatrix
NumericMatrix ex_intensities2qmatrix(const NumericVector& ex_intensities);
RcppExport SEXP _cvalr_ex_intensities2qmatrix(SEXP ex_intensitiesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type ex_intensities(ex_intensitiesSEXP);
    rcpp_result_gen = Rcpp::wrap(ex_intensities2qmatrix(ex_intensities));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cvalr_multiply_binomial_coefficient", (DL_FUNC) &_cvalr_multiply_binomial_coefficient, 3},
    {"_cvalr_is_qmatrix", (DL_FUNC) &_cvalr_is_qmatrix, 2},
    {"_cvalr_portfolio_cds_coupon", (DL_FUNC) &_cvalr_portfolio_cds_coupon, 4},
    {"_cvalr_portfolio_cds_upfront", (DL_FUNC) &_cvalr_portfolio_cds_upfront, 5},
    {"_cvalr_portfolio_cds_equation", (DL_FUNC) &_cvalr_portfolio_cds_equation, 6},
    {"_cvalr_cdo_upfront", (DL_FUNC) &_cvalr_cdo_upfront, 6},
    {"_cvalr_cdo_coupon", (DL_FUNC) &_cvalr_cdo_coupon, 5},
    {"_cvalr_cdo_equation", (DL_FUNC) &_cvalr_cdo_equation, 7},
    {"_cvalr_ex_intensities2qmatrix", (DL_FUNC) &_cvalr_ex_intensities2qmatrix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cvalr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
