# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Portfolio CDS spread
#'
#' @param expected_losses The expected losses of the portfolio (accounting
#'   for recovery) at `times`
#' @param expected_nominals The expected nominal values of the portfolio
#'   (accounting for expected accrued interest) at `times`
#' @param times The times of the payment schedule
#' @param discount_factors The discount factors.
#'
#' @export
portfolio_cds_spread <- function(expected_losses, expected_nominals, times, discount_factors) {
    .Call(`_cvalr_portfolio_cds_spread`, expected_losses, expected_nominals, times, discount_factors)
}

