# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiply_binomial_coefficient <- function(x, n, k) {
    .Call(`_cvalr_multiply_binomial_coefficient`, x, n, k)
}

#' Portfolio CDS spread and CDO methods
#'
#' @param expected_losses The expected losses (not including recovered part)
#' @param times The times of the payment schedule
#' @param discount_factors The discount factors.
#' @param recovery_rate The recovery rate
#'
#' @name cdx
#' @export
portfolio_cds_coupon <- function(expected_losses, times, discount_factors, recovery_rate) {
    .Call(`_cvalr_portfolio_cds_coupon`, expected_losses, times, discount_factors, recovery_rate)
}

#' @rdname cdx
#'
#' @param coupon The periodically paid coupon of the payment leg
#' @param upfront The upfront payment
#'
#' @export
portfolio_cds_upfront <- function(expected_losses, times, discount_factors, recovery_rate, coupon) {
    .Call(`_cvalr_portfolio_cds_upfront`, expected_losses, times, discount_factors, recovery_rate, coupon)
}

#' @rdname cdx
#'
#' @param upfront The upfront payment
#'
#' @export
portfolio_cds_equation <- function(expected_losses, times, discount_factors, recovery_rate, coupon, upfront) {
    .Call(`_cvalr_portfolio_cds_equation`, expected_losses, times, discount_factors, recovery_rate, coupon, upfront)
}

#' @rdname cdx
#'
#' @param lower Lower attachment of the CDO tranche
#' @param upper Upper attachment of the CDO tranche
#'
#' @export
cdo_upfront <- function(expected_losses, times, discount_factors, lower, upper, coupon) {
    .Call(`_cvalr_cdo_upfront`, expected_losses, times, discount_factors, lower, upper, coupon)
}

#' @rdname cdx
#'
#' @export
cdo_coupon <- function(expected_losses, times, discount_factors, lower, upper) {
    .Call(`_cvalr_cdo_coupon`, expected_losses, times, discount_factors, lower, upper)
}

#' @rdname cdx
#'
#' @export
cdo_equation <- function(expected_losses, times, discount_factors, lower, upper, coupon, upfront) {
    .Call(`_cvalr_cdo_equation`, expected_losses, times, discount_factors, lower, upper, coupon, upfront)
}

ex_intensities2qmatrix <- function(ex_intensities) {
    .Call(`_cvalr_ex_intensities2qmatrix`, ex_intensities)
}

