# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Portfolio CDS spread and CDO methods
#'
#' @param expected_default_counts The expected default counts of the portfolio
#'   at `times`
#' @param times The times of the payment schedule
#' @param discount_factors The discount factors.
#' @param recovery_rate The recovery rate
#'
#' @name cdx
#' @export
portfolio_cds_spread <- function(expected_default_counts, times, discount_factors, recovery_rate) {
    .Call(`_cvalr_portfolio_cds_spread`, expected_default_counts, times, discount_factors, recovery_rate)
}

